// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title EnergyMarket
 * @dev This contract serves as the decentralized ledger for a P2P energy market.
 * It manages energy balances for prosumers and records peer-to-peer transactions.
 * It's designed to be owned by a central entity (e.g., an AI controller) that
 * manages prosumer registration and initiates trades.
 */
contract EnergyMarket is Ownable {
    // Add a constructor that takes the initial owner's address
    // and passes it to the Ownable constructor.
    constructor(address initialOwner) Ownable(initialOwner) {}

    // STRUCT to define a single energy transaction, providing a clear data structure.
    struct Transaction {
        address sender;
        address receiver;
        uint256 amountInKwh;
        uint256 timestamp;
    }

    // MAPPING to explicitly track which addresses are registered prosumers.
    mapping(address => bool) public isProsumer;

    // MAPPING to store the energy balance (in kWh) for each prosumer address.
    // This acts as a decentralized database for each user's energy credit.
    mapping(address => uint256) public prosumerEnergyBalance;

    // ARRAY to store all completed transactions, creating a public and immutable history.
    Transaction[] public transactionHistory;

    // EVENTS for real-time off-chain monitoring. These are crucial for the FastAPI backend
    // to listen for updates without polling the contract state.
    event ProsumerRegistered(address indexed prosumer);
    event EnergyReported(address indexed prosumer, uint256 newBalance);
    event TradeCompleted(
        address indexed seller,
        address indexed buyer,
        uint256 amountInKwh,
        uint256 timestamp
    );

    // Modifier to restrict certain actions to only registered prosumers.
    // This enhances security and prevents unauthorized actions.
    modifier onlyProsumer() {
        require(isProsumer[msg.sender], "Only registered prosumers can perform this action.");
        _;
    }

    /**
     * @dev Registers a new prosumer (e.g., a Nanogrid) with a zero balance.
     * This function can only be called by the contract owner (your AI controller).
     * @param _prosumer The address of the new prosumer to register.
     */
    function registerProsumer(address _prosumer) public onlyOwner {
        require(!isProsumer[_prosumer], "Prosumer is already registered.");
        isProsumer[_prosumer] = true;
        prosumerEnergyBalance[_prosumer] = 0;
        emit ProsumerRegistered(_prosumer);
    }

    /**
     * @dev Records energy surplus from a prosumer. This simulates a smart meter
     * reporting energy generated by solar panels.
     * @param _surplusInKwh The amount of energy (in kWh) to add to the prosumer's balance.
     */
    function reportEnergySurplus(uint256 _surplusInKwh) public onlyProsumer {
        prosumerEnergyBalance[msg.sender] += _surplusInKwh;
        emit EnergyReported(msg.sender, prosumerEnergyBalance[msg.sender]);
    }

    /**
     * @dev Executes a P2P energy trade between a seller and a buyer.
     * This function is the core of your decentralized market logic.
     * @param _buyer The address of the prosumer buying the energy.
     * @param _amountInKwh The amount of energy (in kWh) to trade.
     */
    function executeP2PTrade(address _buyer, uint256 _amountInKwh) public onlyProsumer {
        require(prosumerEnergyBalance[msg.sender] >= _amountInKwh, "Insufficient energy balance.");
        require(isProsumer[_buyer], "Invalid buyer address");

        // Update balances for both seller (msg.sender) and buyer
        prosumerEnergyBalance[msg.sender] -= _amountInKwh;
        prosumerEnergyBalance[_buyer] += _amountInKwh;

        // Record the transaction to the public history
        transactionHistory.push(Transaction(msg.sender, _buyer, _amountInKwh, block.timestamp));

        // Emit an event to notify off-chain systems
        emit TradeCompleted(msg.sender, _buyer, _amountInKwh, block.timestamp);
    }

    /**
     * @dev Retrieves the full history of all completed transactions.
     * @return An array of all transaction structs.
     */
    function getTransactions() public view returns (Transaction[] memory) {
        return transactionHistory;
    }
}